const pool = require('../config/db');

// ── CONFIG HISTORY ───────────────────────────────────────────────────────────
// Audit log of the admin's contest saves. Each save-config writes one row that
// snapshots the post-save state (settings + contestants + criteria) plus the
// ui_cache design already present for that save (design_type 'ai' | 'default'
// and its prompt_hash), so the admin can inspect, view, and delete past saves.

function parseSnapshot(value) {
  if (value == null) return null;
  try {
    return typeof value === 'string' ? JSON.parse(value) : value;
  } catch {
    return null;
  }
}

// The ui_cache row matching this save (if any). The save runs BEFORE the AI/
// default UI is (re)generated by /stream-ui, so this is the design already on
// disk at save time — exactly what the old saves point at.
async function latestUiCache(schoolId) {
  const [rows] = await pool.execute(
    `SELECT design_type, prompt_hash
       FROM ui_cache
      WHERE school_id = ?
      ORDER BY updated_at DESC, id DESC
      LIMIT 1`,
    [schoolId]
  );
  return rows[0] || {};
}

// Read back the post-commit state so partial saves (e.g. lock toggle) still
// produce a complete, accurate snapshot.
async function buildSnapshot(schoolId) {
  const [settings] = await pool.execute(
    'SELECT * FROM settings WHERE school_id = ? LIMIT 1',
    [schoolId]
  );
  const [contestants] = await pool.execute(
    'SELECT id, name, entry_number FROM contestants WHERE school_id = ? ORDER BY entry_number ASC, id ASC',
    [schoolId]
  );
  const [criteria] = await pool.execute(
    'SELECT id, name, percentage FROM criteria WHERE school_id = ? ORDER BY id ASC',
    [schoolId]
  );
  return { settings: settings[0] || null, contestants, criteria };
}

// ── WRITE ───────────────────────────────────────────────────────────────────
async function addHistory(schoolId) {
  const snapshot = await buildSnapshot(schoolId);
  const cache    = await latestUiCache(schoolId);
  const s        = snapshot.settings || {};

  const [result] = await pool.execute(
    `INSERT INTO config_history
       (school_id, contest_name, judge_count, ui_mode, design_type, prompt_hash,
        computation_type, tie_break_method, snapshot)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      schoolId,
      s.contest_name     || null,
      s.judge_count      != null ? Number(s.judge_count) : null,
      s.ui_mode          || null,
      cache.design_type  || null,
      cache.prompt_hash  || null,
      s.computation_type || null,
      s.tie_break_method || null,
      JSON.stringify(snapshot),
    ]
  );

  return { id: result.insertId };
}

// Backfills the most recent history row with the design actually written to
// ui_cache for that save. saveConfig logs the row BEFORE /stream-ui generates
// the design, so this runs right after the ui_cache write to make the row's
// design_type/prompt_hash reflect the design THIS save produced.
async function updateDesign(schoolId, designType, promptHash) {
  const [result] = await pool.execute(
    `UPDATE config_history
        SET design_type = ?, prompt_hash = ?
      WHERE school_id = ?
      ORDER BY id DESC
      LIMIT 1`,
    [designType || null, promptHash || null, schoolId]
  );
  return result.affectedRows > 0;
}

// ── READ ────────────────────────────────────────────────────────────────────
// List view — returns lightweight rows (no snapshot payload) with derived
// contestant/criteria counts so the table renders fast.
async function getHistory(schoolId) {
  const [rows] = await pool.execute(
    `SELECT id, contest_name, judge_count, ui_mode, design_type, prompt_hash,
            computation_type, tie_break_method, created_at, snapshot
       FROM config_history
      WHERE school_id = ?
      ORDER BY id DESC`,
    [schoolId]
  );

  return rows.map((r) => {
    const snapshot = parseSnapshot(r.snapshot);
    return {
      id:                r.id,
      contest_name:      r.contest_name,
      judge_count:       r.judge_count,
      ui_mode:           r.ui_mode,
      design_type:       r.design_type,
      prompt_hash:       r.prompt_hash,
      computation_type:  r.computation_type,
      tie_break_method:  r.tie_break_method,
      contestants:       snapshot?.contestants?.length || 0,
      criteria:          snapshot?.criteria?.length    || 0,
      created_at:        r.created_at,
    };
  });
}

async function getHistoryById(schoolId, id) {
  const [rows] = await pool.execute(
    'SELECT * FROM config_history WHERE school_id = ? AND id = ? LIMIT 1',
    [schoolId, id]
  );
  if (!rows[0]) return null;
  const r = rows[0];
  return {
    ...r,
    snapshot: parseSnapshot(r.snapshot),
  };
}

// ── DELETE ──────────────────────────────────────────────────────────────────
async function deleteHistory(schoolId, ids) {
  const list = Array.isArray(ids)
    ? ids.map(Number).filter((n) => Number.isInteger(n) && n > 0)
    : [];
  if (!list.length) return { success: true, deleted: 0 };

  const placeholders = list.map(() => '?').join(',');
  const [result] = await pool.execute(
    `DELETE FROM config_history WHERE school_id = ? AND id IN (${placeholders})`,
    [schoolId, ...list]
  );
  return { success: true, deleted: result.affectedRows };
}

async function deleteAllHistory(schoolId) {
  const [result] = await pool.execute(
    'DELETE FROM config_history WHERE school_id = ?',
    [schoolId]
  );
  return { success: true, deleted: result.affectedRows };
}

module.exports = {
  addHistory,
  updateDesign,
  getHistory,
  getHistoryById,
  deleteHistory,
  deleteAllHistory,
};